name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Deploy
        uses: benmatselby/hugo-deploy-gh-pages@main
        env:
          HUGO_VERSION: "0.162.0"
          HUGO_EXTENDED: true
          TARGET_REPO: mjbecerra/mjbecerra.github.io
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: '--minify'
